// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/all': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/all.get').default>>>>
    }
    '/api/env': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/env.get').default>>>>
    }
    '/api/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/login.post').default>>>>
    }
    '/api/public-replies/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/public-replies/[id].get').default>>>>
    }
    '/api/public-topic/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/public-topic/[id].get').default>>>>
    }
    '/api/replies/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/replies/[id].get').default>>>>
    }
    '/api/s/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/s/[id].get').default>>>>
    }
    '/api/t/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/t/[id].get').default>>>>
    }
    '/api/topic/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/topic/[id].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.store/@nuxt+nitro-server@3.21.2/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}